In [8]:
import numpy as np
from numpy import linalg as LA


In [9]:
A = np.array([[-2,0],[-1,3],[1,3]])

In [10]:
A

array([[-2,  0],
       [-1,  3],
       [ 1,  3]])

In [11]:
B = np.array([[0,-2,2],[-2,3,2]])

In [12]:
B

array([[ 0, -2,  2],
       [-2,  3,  2]])

## Matrix multiplication

In [14]:
C = np.matmul(A,B)

In [15]:
C

array([[ 0,  4, -4],
       [-6, 11,  4],
       [-6,  7,  8]])

In [16]:
D = np.matmul(B,A)

In [17]:
D

array([[ 4,  0],
       [ 3, 15]])

## Determinant and inverse

In [18]:
E = np.array([[3,4,-1],[2,0,1],[1,3,-2]])

In [19]:
E

array([[ 3,  4, -1],
       [ 2,  0,  1],
       [ 1,  3, -2]])

### Determinant

In [22]:
detE = LA.det(E)

In [23]:
detE

5.000000000000001

### Inverse

In [25]:
invE = LA.inv(E)

In [26]:
invE

array([[-0.6,  1. ,  0.8],
       [ 1. , -1. , -1. ],
       [ 1.2, -1. , -1.6]])

### Test

In [27]:
np.dot(E,invE)

array([[ 1.00000000e+00,  2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [29]:
np.allclose(np.dot(E,invE),np.eye(E.shape[0]))
                

True

## Eingenvector and eingenvalue 

In [31]:
F = np.array([[1,-1,0],[-1,2,1],[0,1,1]])

In [32]:
F

array([[ 1, -1,  0],
       [-1,  2,  1],
       [ 0,  1,  1]])

In [36]:
values,vector = LA.eig(F)

In [37]:
vector

array([[-4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
       [ 8.16496581e-01,  2.48915666e-16, -5.77350269e-01],
       [ 4.08248290e-01, -7.07106781e-01,  5.77350269e-01]])

In [38]:
values

array([ 3.00000000e+00,  1.00000000e+00, -5.13860489e-17])

## F power 666

### F can be transform into a diagonal matrix with the previous given eingeinvalue

In [67]:
d = np.zeros((3,3))

In [78]:
d

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [81]:
np.fill_diagonal(d,values)

In [82]:
d

array([[ 3.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -5.13860489e-17]])

In [86]:

F666 = LA.matrix_power(d,666)

In [87]:
F666

array([[inf,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])