# Numpy basic introduction 


In [1]:
import numpy as np

## 1. Create a list of 3 lines and 5 columms initialized to zero

In [15]:
A = np.zeros((3,5),dtype=np.int16) 

In [37]:
A


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [38]:
A.ndim


2

## 2. Create a list of 5 lines and 4 colummns initialized to 1

In [17]:
B = np.ones((5,4),dtype=np.int16)

In [18]:
B

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

## 3. Create a list of (5,5) initialized to 666

In [6]:
C = np.full((5,5),666)

In [7]:
C

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## 4. Create a list of (5,5) equal to identity matrix

In [8]:
D = np.eye(5)

In [9]:
D

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 5. Test of function  "add" of numpy

In [11]:
E= np.add(C,D)

In [12]:
E

array([[667., 666., 666., 666., 666.],
       [666., 667., 666., 666., 666.],
       [666., 666., 667., 666., 666.],
       [666., 666., 666., 667., 666.],
       [666., 666., 666., 666., 667.]])

### The function np.add(C,D) return a Matrix which is the sum of matrix C and D

## 6. Test of numpy multiplication

In [13]:
F = np.multiply(C,D)

In [14]:
F


array([[666.,   0.,   0.,   0.,   0.],
       [  0., 666.,   0.,   0.,   0.],
       [  0.,   0., 666.,   0.,   0.],
       [  0.,   0.,   0., 666.,   0.],
       [  0.,   0.,   0.,   0., 666.]])

### np.multiply is not a matrix product, it multiply terms at the same line and column

## 7. Create a list with random numbers

In [19]:
G = np.random.randint(0,9,(3,5))

In [20]:
G

array([[0, 5, 1, 7, 1],
       [7, 6, 6, 8, 4],
       [5, 3, 2, 3, 5]])


## 8. Sort the previous array per lines

In [21]:
H = np.sort(G,axis=0)

In [22]:
H

array([[0, 3, 1, 3, 1],
       [5, 5, 2, 7, 4],
       [7, 6, 6, 8, 5]])

## 9. Sort the previous array per columns

In [24]:
I = np.sort(G,axis=1)

In [25]:
I

array([[0, 1, 1, 5, 7],
       [4, 6, 6, 7, 8],
       [2, 3, 3, 5, 5]])

## 10. Sort all values

In [26]:
J = np.sort(G)

In [27]:
J

array([[0, 1, 1, 5, 7],
       [4, 6, 6, 7, 8],
       [2, 3, 3, 5, 5]])

## 11. 1D array with values range from 0 to 35

In [33]:
K = np.arange(0,36)


In [34]:
K

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

## 12. Reshape the previous array

In [39]:
L = np.reshape(K,(4,9))

In [40]:
L

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

## 13. Extract From L an array of (2,3)

In [42]:
M = L[:2,:3]

In [43]:
M

array([[ 0,  1,  2],
       [ 9, 10, 11]])

## 14. Show attributes 

### Shape

In [44]:
M.shape

(2, 3)

In [48]:
L.shape

(4, 9)

### Size

In [45]:
M.size

6

In [49]:
L.size

36

### Dimension


In [46]:
M.ndim

2

In [50]:
L.ndim

2

### Type

In [47]:
M.dtype

dtype('int32')

In [51]:
L.dtype

dtype('int32')

## 15. Evaluate 2L

In [59]:
N = 2*L

In [60]:
L

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [61]:
N

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46, 48, 50, 52],
       [54, 56, 58, 60, 62, 64, 66, 68, 70]])

## 16. Sum lines

In [66]:
O = np.sum(L, axis=0)

In [67]:
O


array([54, 58, 62, 66, 70, 74, 78, 82, 86])

## 17. Sum columns

In [73]:
P = np.sum(L,axis=1)

In [74]:
P

array([ 36, 117, 198, 279])

## 18. Sum all

In [75]:
Q = np.sum(L)

In [76]:
Q

630

## 19. Replace value  

In [79]:
L[1][2] = 666

In [80]:
L

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10, 666,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20, 666,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35]])

In [81]:
K

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 666,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 666,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35])

### K is modify as L. L is a reference of K

## 20. Extract an array from L

In [84]:
R = L[1:3,2:6]

In [85]:
R

array([[666,  12,  13,  14],
       [ 20, 666,  22,  23]])