# numoy command

In [2]:
import numpy as np

In [3]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [4]:
sample_array.dtype

dtype('int32')

In [5]:
ones = np.ones((2,3))

In [6]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
range_array = np.arange(2,25,4)
range_array

array([ 2,  6, 10, 14, 18, 22])

In [13]:
np.random.seed(seed=99999)
random_array = np.random.randint(10, size=(5,3))
random_array

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [14]:
a = np.random.randint(10, size=(2,3,4,5))
a

array([[[[2, 0, 0, 5, 0],
         [0, 8, 1, 0, 9],
         [7, 1, 8, 9, 5],
         [8, 3, 4, 2, 1]],

        [[5, 5, 8, 3, 4],
         [6, 9, 6, 9, 4],
         [6, 5, 5, 8, 8],
         [7, 4, 0, 9, 2]],

        [[0, 7, 2, 8, 1],
         [2, 9, 4, 4, 4],
         [3, 3, 4, 1, 0],
         [1, 3, 0, 5, 8]]],


       [[[7, 7, 5, 4, 6],
         [8, 7, 6, 4, 7],
         [4, 4, 4, 2, 5],
         [7, 2, 2, 0, 8]],

        [[1, 5, 5, 5, 6],
         [9, 0, 7, 7, 6],
         [2, 5, 0, 9, 1],
         [0, 6, 9, 9, 3]],

        [[2, 3, 2, 4, 0],
         [6, 0, 2, 0, 6],
         [9, 5, 4, 1, 7],
         [5, 7, 8, 2, 7]]]])