In [1]:
import numpy as np
import pandas as pd
# Création du tableau A de 3 lignes et 5 colonnes avec des zéros
A = np.zeros((3, 5), dtype=int)

# Création du tableau B de 5 lignes et 4 colonnes avec des uns
B = np.ones((5, 4), dtype=int)

# Création du tableau C de 5 lignes et 5 colonnes avec des 666
C = np.full((5, 5), 666, dtype=int)

print(" A ", A)
print("B ", B)
print("C ", C)

 A  [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
B  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
C  [[666 666 666 666 666]
 [666 666 666 666 666]
 [666 666 666 666 666]
 [666 666 666 666 666]
 [666 666 666 666 666]]


In [4]:
# Création du tableau D de 5 lignes et 5 colonnes avec une diagonale de 1
D = np.eye(5, dtype=int)
print(" D \n", D)

# Calcul de la somme E de C et D
E = np.add(C, D)
print("E", E)


 D 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

E 
 [[667 666 666 666 666]
 [666 667 666 666 666]
 [666 666 667 666 666]
 [666 666 666 667 666]
 [666 666 666 666 667]]


In [5]:
# Calcul du produit F de C par D
F = np.multiply(C, D)
print("\n F \n", F)

G = np.random.randint(0, 10, size=(3, 5))
print(" G \n", G)


 F 
 [[666   0   0   0   0]
 [  0 666   0   0   0]
 [  0   0 666   0   0]
 [  0   0   0 666   0]
 [  0   0   0   0 666]]
 G 
 [[5 1 2 3 0]
 [7 0 4 3 6]
 [1 6 7 4 8]]


In [7]:
# Tri de G ligne par ligne 
H = np.sort(G, axis=1)

# Affichage du résultat H (G trié ligne par ligne)
print("\nTableau H (G trié ligne par ligne):\n", H)

# Tri de G colonne par colonne 
I = np.sort(G, axis=0)

# Affichage du résultat I (G trié colonne par colonne)
print("\n I \n", I)

# Tri de l'ensemble des valeurs de G 
J = np.sort(G, axis=None)

# Affichage du résultat J 
print("\n J \n", J)




Tableau H (G trié ligne par ligne) :
 [[0 1 2 3 5]
 [0 3 4 6 7]
 [1 4 6 7 8]]

 I 
 [[1 0 2 3 0]
 [5 1 4 3 6]
 [7 6 7 4 8]]

 J 
 [0 0 1 1 2 3 3 4 4 5 6 6 7 7 8]


In [8]:
# Créer un tableau unidimensionnel K avec tous les entiers de 0 à 35
K = np.arange(36)
print(K)
# Restructurer K sous la forme d'un tableau L de 4 lignes et 9 colonnes
L = K.reshape(4, 9)
print(L)
# Tronquer L sous la forme d'un tableau M de 2 lignes et 3 colonnes
M = L[:2, :3]
print(M)
# Afficher les attributs shape, size, ndim et dtype de L
print("Shape de L:", L.shape)
print("Size de L:", L.size)
print("Nombre de dimensions de L:", L.ndim)
print("Type de données de L:", L.dtype)

# Calculer le tableau N dont les valeurs sont le double de celles de L
N = 2 * L

# Utiliser la méthode "sum" de Numpy pour additionner les valeurs de L ligne par ligne
O = np.sum(L, axis=1)

# Utiliser la méthode "sum" de Numpy pour additionner les valeurs de L colonne par colonne
P = np.sum(L, axis=0)

# Utiliser la méthode "sum" de Numpy pour additionner l'ensemble des valeurs de L
Q = np.sum(L)

# Remplacer la valeur située sur la 2-ème ligne et 3-ème colonne de L par 666
L[1, 2] = 666

# Afficher K pour constater les modifications
print("K après modification de L:", K)

# Créer un tableau R contenant les valeurs de L situées entre les lignes 2 et 3 et les colonnes 3 à 6 (incluses)
R = L[1:3, 3:7]

# Afficher les tableaux M, N, O, P, Q, et R
print("Tableau M:")
print(M)
print("\nTableau N:")
print(N)
print("\nTableau O:")
print(O)
print("\nTableau P:")
print(P)
print("\nTableau Q:")
print(Q)
print("\nTableau R:")
print(R)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]
[[ 0  1  2]
 [ 9 10 11]]
Shape de L: (4, 9)
Size de L: 36
Nombre de dimensions de L: 2
Type de données de L: int64
K après modification de L: [  0   1   2   3   4   5   6   7   8   9  10 666  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35]
Tableau M:
[[  0   1   2]
 [  9  10 666]]

Tableau N:
[[ 0  2  4  6  8 10 12 14 16]
 [18 20 22 24 26 28 30 32 34]
 [36 38 40 42 44 46 48 50 52]
 [54 56 58 60 62 64 66 68 70]]

Tableau O:
[ 36 117 198 279]

Tableau P:
[54 58 62 66 70 74 78 82 86]

Tableau Q:
630

Tableau R:
[[12 13 14 15]
 [21 22 23 24]]


In [14]:
# Les vecteurs u et v
u = np.array([[1], [0], [-3], [2]])
print(u)
v = np.array([[1], [-1], [-2], [2]])
print(v)
#produit scalaire euclidien de u et v
p_s = np.dot(u.T, v)
print("Produit scalaire de u et v", p_s)

# Calcul des normes de u et v
norme_m_u = np.linalg.norm(u, ord=1)
norme_m_v = np.linalg.norm(v, ord=1)
norme_e_u = np.linalg.norm(u, ord=2)
norme_e_v = np.linalg.norm(v, ord=2)
norme_c_u = np.linalg.norm(u, ord=np.inf)
norme_c_v = np.linalg.norm(v, ord=np.inf)

print("Norme de Manhattan de u", norme_m_u)
print("Norme de Manhattan de v", norme_m_v)
print("Norme Euclidienne de u", norme_e_u)
print("Norme Euclidienne de v", norme_e_v)
print("Norme de Chebyshev de u ", norme_c_u)
print("Norme de Chebyshev de v ", norme_c_v)

[[ 1]
 [ 0]
 [-3]
 [ 2]]
[[ 1]
 [-1]
 [-2]
 [ 2]]
Produit scalaire de u et v [[11]]
Norme de Manhattan de u 6.0
Norme de Manhattan de v 6.0
Norme Euclidienne de u 3.7416573867739413
Norme Euclidienne de v 3.1622776601683795
Norme de Chebyshev de u  3.0
Norme de Chebyshev de v  2.0


In [15]:
#la matrice A 
A = np.array([[-2, 0],[-1, 3], [1, 3]])
             
# la matrice B 
B = np.array([[0, -2, 2],[-2, 3, 2]])
             
# C = AB
C = np.dot(A, B)
# D = BA
D = np.dot(B, A)
print("Produit C = AB", C)
print("Produit D = BA", D)


Produit C = AB [[ 0  4 -4]
 [-6 11  4]
 [-6  7  8]]
Produit D = BA [[ 4  0]
 [ 3 15]]


In [16]:
#La matrice E
E = np.array([[3, 4, -1],[2, 0, 1],[1, 3, -2]])
# Dterminant de E
det_E = np.linalg.det(E)
# Inverse de E
inv_E = np.linalg.inv(E)

print("Déterminant de E :", det_E)
print("Inverse de E", inv_E)


Déterminant de E : 5.000000000000003
Inverse de E [[-0.6  1.   0.8]
 [ 1.  -1.  -1. ]
 [ 1.2 -1.  -1.6]]


In [19]:
# La matrice F
F = np.array([[1, -1, 0],[-1, 2, 1], [0, 1, 1]])

# Calcul des valeurs propres et vecteurs propres de F
valeurs_p, vecteurs_p = np.linalg.eig(F)

print("Valeurs propres de F ", valeurs_p)
print("Vecteurs propres de F", vecteurs_p)

Valeurs propres de F  [ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]
Vecteurs propres de F [[-4.08248290e-01 -7.07106781e-01 -5.77350269e-01]
 [ 8.16496581e-01  2.61214948e-16 -5.77350269e-01]
 [ 4.08248290e-01 -7.07106781e-01  5.77350269e-01]]


In [20]:

# La puissance 666 de la matrice F
G = np.linalg.matrix_power(F, 666)

print("Matrice G ", G)


Matrice G (F puissance 666) :
 [[ 7128986253539690578  4188771566630170461 -7128986253539690577]
 [ 4188771566630170461 -8377543133260340922 -4188771566630170461]
 [-7128986253539690577 -4188771566630170461  7128986253539690578]]


## PANDAS

In [28]:
# La série w
w = pd.Series([20, 11, 21, 20, 12, 14])
print(w)

0    20
1    11
2    21
3    20
4    12
5    14
dtype: int64


In [29]:
# Renommer les index de w
w.rename(index={0: 'Federer', 1: 'Borg', 2: 'Nadal', 3: 'Djokovic', 4: 'Emerson', 5: 'Sampras'}, inplace=True)
print("Série w\n", w)

# Nouvelle série w1 en spécifiant les index
w1 = pd.Series([20, 11, 21, 20, 12, 14], index=['Federer', 'Borg', 'Nadal', 'Djokovic', 'Emerson', 'Sampras'])
print("Nouvelle série w1\n", w1)

# Création de w2 en passant un dictionnaire en paramètre
Valeurs = {'Federer': 20, 'Borg': 11, 'Nadal': 21, 'Djokovic': 20, 'Emerson': 12, 'Sampras': 14}
w2 = pd.Series(Valeurs)
print("La série w2\n", w2)

Série w
 Federer     20
Borg        11
Nadal       21
Djokovic    20
Emerson     12
Sampras     14
dtype: int64
Nouvelle série w1
 Federer     20
Borg        11
Nadal       21
Djokovic    20
Emerson     12
Sampras     14
dtype: int64
La série w2
 Federer     20
Borg        11
Nadal       21
Djokovic    20
Emerson     12
Sampras     14
dtype: int64


In [18]:
#loc pour accéder à la valeur d'index 'Borg'
borg_loc = w.loc['Borg']
print("Index Borg", borg_loc)

#iloc pour accéder à la valeur à la deuxième position
borg_iloc = w.iloc[1]
print("la valeur à la position 1", borg_iloc)

Valeur de l'index 'Borg' avec loc : 11
Valeur à la position 1 (correspondant à 'Borg') avec iloc : 11


In [17]:
valeurs_iloc = w.iloc[1:5]
print("Valeurs de 'Borg' à 'Emerson' avec iloc :\n", valeurs_borg_emerson_iloc)

Valeurs de 'Borg' à 'Emerson' avec iloc :
 1    11
2    21
3    20
4    12
dtype: int64


In [20]:
import pandas as pd

data = {
    'Number': [20, 11, 21, 20, 12, 14, 11],
    'Nationality': ["Swiss", "Sweden", "Spain", "Serbia", "Australia", "USA", "Australia"],
    'Born': [1981, 1956, 1986, 1987, 1936, 1971, 1938]
}
index_data = ["Federer", "Borg", "Nadal", "Djokovic", "Emerson", "Sampras", "Laver"]

# Création du DataFrame à partir du dictionnaire 
best = pd.DataFrame(data, index=index_data)
print(best)

# Affichage des attributs
print("Shape", best.shape)
print("Size", best.size)
print("Ndim", best.ndim)
print("Dtypes", best.dtypes)
print("Index", best.index)
print("Values", best.values)
print("Columns", best.columns)

print("Info")
best.info()


          Number Nationality  Born
Federer       20       Swiss  1981
Borg          11      Sweden  1956
Nadal         21       Spain  1986
Djokovic      20      Serbia  1987
Emerson       12   Australia  1936
Sampras       14         USA  1971
Laver         11   Australia  1938
Shape: (7, 3)
Size: 21
Ndim: 2
Dtypes: Number          int64
Nationality    object
Born            int64
dtype: object
Index: Index(['Federer', 'Borg', 'Nadal', 'Djokovic', 'Emerson', 'Sampras', 'Laver'], dtype='object')
Values: [[20 'Swiss' 1981]
 [11 'Sweden' 1956]
 [21 'Spain' 1986]
 [20 'Serbia' 1987]
 [12 'Australia' 1936]
 [14 'USA' 1971]
 [11 'Australia' 1938]]
Columns: Index(['Number', 'Nationality', 'Born'], dtype='object')

Info:
<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Federer to Laver
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Number       7 non-null      int64 
 1   Nationality  7 non-null      object
 2   Bo

In [21]:
# Accès à une colonne avec data['NomColonne']
col_numbre = best['Number']
print("Colonne 'Number'")
print(col_numbre)

# Accès à une colonne avec data.NomColonne
nationality = best.Nationality
print("colonne 'Nationality'")
print(nationality)

Colonne 'Number' (syntaxe data['NomColonne']):
Federer     20
Borg        11
Nadal       21
Djokovic    20
Emerson     12
Sampras     14
Laver       11
Name: Number, dtype: int64

Colonne 'Nationality' (syntaxe data.NomColonne):
Federer         Swiss
Borg           Sweden
Nadal           Spain
Djokovic       Serbia
Emerson     Australia
Sampras           USA
Laver       Australia
Name: Nationality, dtype: object


In [35]:
#l'année de naissance de 'Borg' avec loc
born_borg_loc = best.loc['Borg', 'Born']
print("Année de naissance de 'Borg' avec loc", born_borg_loc)

#l'année de naissance de 'Borg' avec iloc
born_borg_iloc = best.iloc[1, 2]  # 'Borg' est à l'index 1, 'Born' est à l'index 2
print("Année de naissance de 'Borg' avec iloc", born_borg_iloc)

# Utilisation du slicing pour accéder à plusieurs valeurs (accéder aux trois premières lignes de la colonne 'Born')
born_slicing = best['Born'][:3]
print("Trois premières années de naissance")
print(born_slicing)

Année de naissance de 'Borg' avec loc 1956
Année de naissance de 'Borg' avec iloc 1956
Trois premières années de naissance
Federer    1981
Borg       1956
Nadal      1986
Name: Born, dtype: int64


In [36]:
# Utilisation de la méthode reset_index pour transformer la colonne d'index en une variable
best_reset = best.reset_index()
# Renommer la colonne d'index en 'FirstName' avec la méthode rename
best_reset = best_reset.rename(columns={'index': 'FirstName'})

# Ajouter une nouvelle colonne 'LastName' avec les prénoms des joueurs
best_reset['LastName'] = best_reset['FirstName']
print(best_reset)

  FirstName  Number Nationality  Born  LastName
0   Federer      20       Swiss  1981   Federer
1      Borg      11      Sweden  1956      Borg
2     Nadal      21       Spain  1986     Nadal
3  Djokovic      20      Serbia  1987  Djokovic
4   Emerson      12   Australia  1936   Emerson
5   Sampras      14         USA  1971   Sampras
6     Laver      11   Australia  1938     Laver


In [40]:
# Réordonner les colonnes avec la méthode reindex
ordre_col = ['FirstName', 'LastName', 'Nationality', 'Born', 'Number']
best_ordre = best_reset.reindex(columns=ordre_col)

# Trie 
best_trie = best_ordre.sort_values(by=['Number', 'Born'], ascending=[False, True])

print(best_trie)

  FirstName  LastName Nationality  Born  Number
2     Nadal     Nadal       Spain  1986      21
0   Federer   Federer       Swiss  1981      20
3  Djokovic  Djokovic      Serbia  1987      20
5   Sampras   Sampras         USA  1971      14
4   Emerson   Emerson   Australia  1936      12
6     Laver     Laver   Australia  1938      11
1      Borg      Borg      Sweden  1956      11


## DataFrame(2)

In [4]:
# Fichier CSV
data_csv = pd.read_csv('exemple.csv')
#fichier Excel
data_excel = pd.read_excel('exemple (1).xlsx')

# Les observations où le prénom est égal à 'Robert'
robert_obs = data_csv[data_csv['prénom'] == 'Robert']
print("Observations pour 'Robert'")
print(robert_obs)

# Les observations où le prénom est dans la liste
liste = ['Venetta', 'Charles', 'Julie', 'Carolyn', 'Melissa', 'Heidi', 'James', 'Pedro', 'Harry', 'Maria']
obs_liste= data_csv[data_csv['prénom'].isin(liste)]
print("Observations pour les prénoms dans la liste")
print(obs_liste)

Observations pour 'Robert'
     Unnamed: 0  prénom      nom  un       deux  trois    quatre  cinq
97           97  Robert    Glahn   1  67.237793      5  0.214249     1
133         133  Robert    Kilby   1  69.271402      7  0.064815     1
190         190  Robert    Gomez   2  64.117791     14  0.117251     1
213         213  Robert  Huskins   4  83.189470     10  0.364812     1
227         227  Robert   Dewing   1  80.166270      6  0.263141     0
346         346  Robert   Isbell   1  73.849589     10  0.011041     1
374         374  Robert    Cantu   2  68.347178      8  0.119056     0
416         416  Robert     Culp   3  70.125220     12  0.392884     0
482         482  Robert  Bingham   1  64.560718     11  0.292543     0
651         651  Robert     Adam   2  71.101132      9  0.138352     0
Observations pour les prénoms dans la liste
     Unnamed: 0   prénom        nom  un       deux  trois    quatre  cinq
55           55    James     Pruitt   0  70.216139     11  0.295354     1


In [5]:
#les observations où la valeur de la variable 'deux' est supérieure à 85
deux_sup_85= data_csv[data_csv['deux'] > 85]
print("Observations où 'deux' est supérieur à 85")
print(deux_sup_85)

Observations où 'deux' est supérieur à 85
     Unnamed: 0    prénom         nom  un        deux  trois    quatre  cinq
1             1     Cheri       Smith   1   92.063177      5  0.057861     0
14           14     Julia    Lavender   2   87.070375      8  0.195840     1
19           19    George      Holder   1   88.183383      9  0.273185     1
33           33    Joseph       Ellis   0   88.506203      8  0.171301     0
36           36      Joel       Gould   2   85.646373      7  0.033430     1
39           39    Debbie       Stein   3   86.104563     11  0.060963     0
51           51      Anna       Davis   1   87.399357     12  0.071074     0
86           86    Amanda    Hennigan   1   85.033337     12  0.009130     1
93           93      John       Elder   3   93.653810     13  0.050714     0
119         119   Dierdre      Gorman   2   85.448952     10  0.181905     0
122         122      Troy        Ruiz   3   86.753576      9  0.118825     1
129         129     Janet       Si

In [6]:
#les observations où la valeur de la variable 'cinq' est égale à 1
cinq_egal_1 = data_csv[data_csv['cinq'] == 1]
print("Observations où 'cinq' est égal à 1")
print(cinq_egal_1)

Observations où 'cinq' est égal à 1
     Unnamed: 0    prénom       nom  un       deux  trois    quatre  cinq
3             3   Carlton      Ross   5  74.460673      8  0.879215     1
4             4     Sally    Foster   2  76.448339     15  0.164219     1
6             6   Shannon  Phillips   2  75.894174     10  0.106176     1
7             7       Pat      Loya   3  73.771323      9  0.120294     1
8             8     Scott    Hashim   1  71.252320     10  0.761736     1
..          ...       ...       ...  ..        ...    ...       ...   ...
659         659    Andres    Flores   2  54.820769     12  0.042071     1
660         660     Julie   Johnson   0  63.343997      9  0.231097     1
662         662  Kathleen    Butler   1  61.669270     12  0.158429     1
663         663       Ian    Valero   3  88.737951     11  0.105516     1
664         664      Jean  Williams   3  76.741943     10  0.063430     1

[347 rows x 8 columns]


In [7]:
#les observations où la valeur de la variable 'deux' est supérieure à 85
# et où la valeur de la variable 'cinq' est égale à 1
OBS1 = data_csv[(data_csv['deux'] > 85) & (data_csv['cinq'] == 1)]

print("Observations où 'deux' est supérieur à 85 et 'cinq' est égal à 1")
print(OBS1)

Observations où 'deux' est supérieur à 85 et 'cinq' est égal à 1
     Unnamed: 0    prénom        nom  un       deux  trois    quatre  cinq
14           14     Julia   Lavender   2  87.070375      8  0.195840     1
19           19    George     Holder   1  88.183383      9  0.273185     1
36           36      Joel      Gould   2  85.646373      7  0.033430     1
86           86    Amanda   Hennigan   1  85.033337     12  0.009130     1
122         122      Troy       Ruiz   3  86.753576      9  0.118825     1
129         129     Janet      Sieja   1  98.202315      8  0.063269     1
261         261     Penny     Coburn   4  85.570476     11  0.315184     1
282         282    Sophie     Zirkle   1  93.557910     10  0.157774     1
339         339      Jack     Galyen   2  85.454605     12  0.093590     1
379         379  Bernardo      Moore   1  85.895360     14  0.092952     1
402         402     Helen  Macdonald   2  93.494868     13  0.309640     1
421         421     Misty   William

In [8]:
#les observations où la valeur de la variable 'deux' est supérieure à 85
# ou où la valeur de la variable 'cinq' est égale à 1
OBS2 = data_csv[(data_csv['deux'] > 85) | (data_csv['cinq'] == 1)]
print("Observations où 'deux' est supérieur à 85 ou 'cinq' est égal à 1")
print(OBS2)

Observations où 'deux' est supérieur à 85 ou 'cinq' est égal à 1
     Unnamed: 0    prénom       nom  un       deux  trois    quatre  cinq
1             1     Cheri     Smith   1  92.063177      5  0.057861     0
3             3   Carlton      Ross   5  74.460673      8  0.879215     1
4             4     Sally    Foster   2  76.448339     15  0.164219     1
6             6   Shannon  Phillips   2  75.894174     10  0.106176     1
7             7       Pat      Loya   3  73.771323      9  0.120294     1
..          ...       ...       ...  ..        ...    ...       ...   ...
659         659    Andres    Flores   2  54.820769     12  0.042071     1
660         660     Julie   Johnson   0  63.343997      9  0.231097     1
662         662  Kathleen    Butler   1  61.669270     12  0.158429     1
663         663       Ian    Valero   3  88.737951     11  0.105516     1
664         664      Jean  Williams   3  76.741943     10  0.063430     1

[368 rows x 8 columns]


In [10]:
#les variables 'un', 'trois' et 'quatre' à l'aide d'un double [ ]
variables = data_csv[['un', 'trois', 'quatre']]
print("Variables 'un', 'trois' et 'quatre'")
print(variables)

#les variables 'un', 'trois' et 'quatre' des observations où la valeur de 'deux' est supérieure à 85
# et la valeur de 'cinq' est égale à 1 en utilisant la méthode loc
condition = (data_csv['deux'] > 85) & (data_csv['cinq'] == 1)
variables_condition = data_csv.loc[condition, ['un', 'trois', 'quatre']]
print("Variables 'un', 'trois' et 'quatre' (deux > 85 et cinq == 1):")
print(variables_condition)

Variables 'un', 'trois' et 'quatre'
     un  trois    quatre
0     4      7  0.653466
1     1      5  0.057861
2     5     16  0.039183
3     5      8  0.879215
4     2     15  0.164219
..   ..    ...       ...
661   3     13  0.077230
662   1     12  0.158429
663   3     11  0.105516
664   3     10  0.063430
665   1      9  0.758167

[666 rows x 3 columns]
Variables 'un', 'trois' et 'quatre' (deux > 85 et cinq == 1):
     un  trois    quatre
14    2      8  0.195840
19    1      9  0.273185
36    2      7  0.033430
86    1     12  0.009130
122   3      9  0.118825
129   1      8  0.063269
261   4     11  0.315184
282   1     10  0.157774
339   2     12  0.093590
379   1     14  0.092952
402   2     13  0.309640
421   1     10  0.522502
434   0     11  0.642841
437   3     11  0.248669
442   3      8  0.096750
458   0     10  0.039916
466   4      9  0.376653
491   5     12  0.744689
547   2      8  0.055929
565   0      9  0.057314
608   1     11  0.636649
622   2     12  0.391622
663